import { ReactQueryProvider } from "@/utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <main>
            {children}
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
